/* Generated by Cython 0.29.32 */

#ifndef __PYX_HAVE__lattice_form
#define __PYX_HAVE__lattice_form

#include "Python.h"

#ifndef __PYX_HAVE_API__lattice_form

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyObject *lattice;
__PYX_EXTERN_C PyObject *atom_set;
__PYX_EXTERN_C PyObject *bonds;
__PYX_EXTERN_C PyObject *event;
__PYX_EXTERN_C PyObject *event_time;
__PYX_EXTERN_C PyObject *event_time_tot;
__PYX_EXTERN_C PyObject *site_list_correspondance;
__PYX_EXTERN_C PyObject *list_site_correspondance;
__PYX_EXTERN_C PyObject *diffuse_candidates;
__PYX_EXTERN_C PyObject *highest_atom;

#endif /* !__PYX_HAVE_API__lattice_form */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initlattice_form(void);
#else
PyMODINIT_FUNC PyInit_lattice_form(void);
#endif

#endif /* !__PYX_HAVE__lattice_form */
